java_test(
    name = "HelloWorldTest",
    srcs = ["HelloWorldTest.java"],
    test_class = "com.chris.hello.HelloWorldTest",
    deps = [
        "@junit//jar", 
        "//src/main/java/com/chris/hello:HelloWorld",
    ],
)